language: scala
scala:
  - 2.12.8
sudo: required
dist: trusty

addons:
  sonarcloud:
    organization: "mcallisto-github"

matrix:
  include:
    - stage: build
      jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.5/0.3.5 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - git clean -xdf
  - mill -i resolve jvm.compile
  - mill -i jvm.compile
  - mill -i resolve jvm.test
  - mill -i jvm.test

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.coursier
