language: scala
sudo: required
dist: trusty

matrix:
  include:
    - stage: build
      env: CI_SCRIPT=ci/test-mill-0.sh
      jdk: oraclejdk8

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.2.7/0.2.7-10-db8525 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - git clean -xdf
  - mill -i all jvm.test

cache:
  directories:
    - $HOME/.coursier
